services:
  fritzconnection:
    build: . 
    image: fritzconnection:latest 
    secrets:
      - user
      - password
    volumes:
      - ./GetPublicIpAdress.py:/GetPublicIpAdress.py 
      - ./out/:/out/:rw
    entrypoint: [ "python", "/GetPublicIpAdress.py" ]
secrets:
  user:
    file: ./fritzbox_user
  password:
    file: ./fritzbox_password