services:
  fritzconnection:
    build: . 
    image: ghcr.io/maystar/fritzpublicconnection/fritzconnection:latest
    secrets:
      - user
      - password
    environment:
      FRITZBOX_USER_FILE: /run/secrets/user
      FRITZBOX_PASSWORD_FILE: /run/secrets/password
      FRITZBOX_ADDRESS: fritz.box
      PUBLIC_ADDRESS_FILE: /out/public_address
      OUTPUT_PREFIX: |- 
        http:
          middlewares:
            ownip-allowlist:
              ipAllowList: 
                sourceRange: 

    volumes:
      - ./out/:/out/:rw
secrets:
  user:
    file: ./fritzbox_user
  password:
    file: ./fritzbox_password