services:
  fritzconnection:
    build: . 
    image: ghcr.io/maystar/fritzpublicconnection/fritzconnection:latest
    secrets:
      - user
      - password
    volumes:
      - ./out/:/out/:rw
secrets:
  user:
    file: ./fritzbox_user
  password:
    file: ./fritzbox_password